use crate::db::models::App;
use crate::error::Result;
use std::path::Path;

fn has_required_artifacts(app: &App, workerd_dir: &Path) -> bool {
    let slug_dir = workerd_dir.join(&app.slug);
    if !slug_dir.is_dir() {
        return false;
    }

    let required_files: &[&str] = match app.framework.as_str() {
        "worker" => &["entry.mjs", "worker.js", "static-assets.mjs"],
        "nuxtjs" | "react-router" => &["entry.mjs", "bundle.mjs", "static-assets.mjs"],
        _ => &[],
    };

    required_files.iter().all(|f| slug_dir.join(f).is_file())
}

pub fn generate_dispatch_config(
    apps: &[App],
    workerd_dir: &Path,
    port: u16,
) -> Result<()> {
    let eligible_apps: Vec<&App> = apps
        .iter()
        .filter(|app| {
            let status_ok = app.status == "running" || app.status == "deploying";
            if !status_ok {
                return false;
            }
            if !has_required_artifacts(app, workerd_dir) {
                tracing::warn!(
                    "Skipping app '{}' ({}) from config: missing workerd artifacts in {:?}",
                    app.slug,
                    app.framework,
                    workerd_dir.join(&app.slug)
                );
                return false;
            }
            true
        })
        .collect();

    let dispatch_code = generate_dispatch_mjs(&eligible_apps);
    std::fs::write(workerd_dir.join("dispatch.mjs"), dispatch_code)?;

    let config_code = generate_config_capnp(&eligible_apps, port);
    std::fs::write(workerd_dir.join("config.capnp"), config_code)?;

    Ok(())
}

fn generate_dispatch_mjs(apps: &[&App]) -> String {
    let mut routes = String::new();
    for app in apps {
        let binding_name = format!("APP_{}", app.slug.to_uppercase().replace('-', "_"));
        routes.push_str(&format!(
            "  \"{}\": \"{}\",\n",
            app.subdomain, binding_name
        ));
    }

    format!(
        r#"// Auto-generated by fugue — do not edit
// Routes requests by subdomain to the appropriate app worker.

const routes = {{
{}}};

export default {{
  async fetch(request, env, ctx) {{
    const url = new URL(request.url);
    const hostname = url.hostname;
    const subdomain = hostname.split(".")[0];

    // Route by subdomain
    const bindingName = routes[subdomain];
    if (bindingName && env[bindingName]) {{
      return env[bindingName].fetch(request);
    }}

    // Unknown subdomain
    return new Response("Not Found", {{ status: 404 }});
  }},
}};
"#,
        routes
    )
}

fn generate_config_capnp(apps: &[&App], port: u16) -> String {
    let mut services = vec![
        "    (name = \"main\", worker = .dispatchWorker),".to_string(),
    ];
    let mut workers = vec![generate_dispatch_worker_def(apps)];
    let mut socket_bindings = String::new();

    for app in apps {
        let slug = &app.slug;

        match app.framework.as_str() {
            "worker" => {
                let service_name = format!("app-{}", slug);
                services.push(format!(
                    "    (name = \"{}\", worker = .{}),",
                    service_name,
                    to_camel_case(slug)
                ));
                workers.push(generate_worker_def(slug, &app.status));
            }
            "nuxtjs" | "react-router" => {
                let app_service = format!("app-{}", slug);
                let ssr_service = format!("ssr-{}", slug);
                let static_service = format!("static-{}", slug);

                services.push(format!(
                    "    (name = \"{}\", worker = .{}),",
                    app_service,
                    entry_camel(slug)
                ));
                services.push(format!(
                    "    (name = \"{}\", worker = .{}),",
                    ssr_service,
                    ssr_camel(slug)
                ));
                services.push(format!(
                    "    (name = \"{}\", worker = .{}),",
                    static_service,
                    static_camel(slug)
                ));

                workers.push(generate_framework_entry_worker_def(slug, &app.status));
                workers.push(generate_framework_ssr_worker_def(slug, &app.status, &app.env_vars));
                workers.push(generate_framework_static_worker_def(slug, &app.status));
            }
            _ => {}
        }
    }

    for (i, service) in services.iter().enumerate() {
        if i > 0 {
            socket_bindings.push('\n');
        }
        socket_bindings.push_str(service);
    }

    let workers_str = workers.join("\n");

    format!(
        r#"using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
{}
  ],
  sockets = [
    ( name = "http",
      address = "*:{}",
      http = (),
      service = "main"
    ),
  ],
);

{}
"#,
        services.join("\n"),
        port,
        workers_str
    )
}

fn generate_dispatch_worker_def(apps: &[&App]) -> String {
    let mut bindings = String::new();
    for app in apps {
        let binding_name = format!("APP_{}", app.slug.to_uppercase().replace('-', "_"));
        let service_name = format!("app-{}", app.slug);
        bindings.push_str(&format!(
            "    (name = \"{}\", service = \"{}\"),\n",
            binding_name, service_name
        ));
    }

    format!(
        r#"const dispatchWorker :Workerd.Worker = (
  modules = [
    (name = "dispatch.mjs", esModule = embed "dispatch.mjs"),
  ],
  compatibilityDate = "2026-04-21",
  compatibilityFlags = ["nodejs_compat"],
  bindings = [
{}
  ],
);"#,
        bindings
    )
}

fn generate_worker_def(slug: &str, _status: &str) -> String {
    let camel = to_camel_case(slug);
    format!(
        r#"const {} :Workerd.Worker = (
  modules = [
    (name = "{}/entry.mjs", esModule = embed "{}/entry.mjs"),
    (name = "{}/worker.js", esModule = embed "{}/worker.js"),
    (name = "{}/static-assets.mjs", esModule = embed "{}/static-assets.mjs"),
  ],
  compatibilityDate = "2026-04-21",
  compatibilityFlags = ["nodejs_compat"],
);"#,
        camel, slug, slug, slug, slug, slug, slug
    )
}

fn generate_framework_entry_worker_def(slug: &str, _status: &str) -> String {
    let camel = entry_camel(slug);
    format!(
        r#"const {0} :Workerd.Worker = (
  modules = [
    (name = "{1}/entry.mjs", esModule = embed "{1}/entry.mjs"),
    (name = "{1}/static-assets.mjs", esModule = embed "{1}/static-assets.mjs"),
  ],
  compatibilityDate = "2026-04-21",
  compatibilityFlags = ["nodejs_compat"],
  bindings = [
    (name = "SSR", service = "ssr-{1}"),
    (name = "STATIC", service = "static-{1}"),
  ],
);"#,
        camel, slug
    )
}

fn generate_framework_ssr_worker_def(slug: &str, _status: &str, env_vars: &serde_json::Value) -> String {
    let camel = ssr_camel(slug);

    let mut bindings = String::from("    (name = \"ASSETS\", service = \"static-{}\"),\n".replace("{}", slug));
    if let Some(obj) = env_vars.as_object() {
        for (key, value) in obj {
            if let Some(str_val) = value.as_str() {
                bindings.push_str(&format!(
                    "    (name = \"{}\", string = \"{}\"),\n",
                    key, str_val.replace('"', "\\\"")
                ));
            }
        }
    }

    format!(
        r#"const {} :Workerd.Worker = (
  modules = [
    (name = "{}/bundle.mjs", esModule = embed "{}/bundle.mjs"),
  ],
  compatibilityDate = "2026-04-21",
  compatibilityFlags = ["nodejs_compat"],
  bindings = [
{}
  ],
);"#,
        camel, slug, slug, bindings.trim_end()
    )
}

fn generate_framework_static_worker_def(slug: &str, _status: &str) -> String {
    let camel = static_camel(slug);
    format!(
        r#"const {} :Workerd.Worker = (
  modules = [
    (name = "{}/static-assets.mjs", esModule = embed "{}/static-assets.mjs"),
  ],
  compatibilityDate = "2026-04-21",
);"#,
        camel, slug, slug
    )
}

fn to_camel_case(slug: &str) -> String {
    slug.split('-')
        .enumerate()
        .map(|(i, part)| {
            if i == 0 {
                part.to_string()
            } else {
                let mut chars = part.chars();
                match chars.next() {
                    Some(c) => format!("{}{}", c.to_uppercase(), chars.as_str()),
                    None => String::new(),
                }
            }
        })
        .collect::<String>()
        + "Worker"
}

fn entry_camel(slug: &str) -> String {
    to_camel_case(slug).replace("Worker", "EntryWorker")
}

fn ssr_camel(slug: &str) -> String {
    to_camel_case(slug).replace("Worker", "SsrWorker")
}

fn static_camel(slug: &str) -> String {
    to_camel_case(slug).replace("Worker", "StaticWorker")
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use uuid::Uuid;

    fn make_app(slug: &str, framework: &str, status: &str) -> App {
        App {
            id: Uuid::new_v4(),
            name: slug.to_string(),
            slug: slug.to_string(),
            subdomain: slug.to_string(),
            framework: framework.to_string(),
            status: status.to_string(),
            description: None,
            env_vars: serde_json::json!({}),
            source_path: None,
            build_path: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn test_to_camel_case_simple() {
        assert_eq!(to_camel_case("my-blog"), "myBlogWorker");
        assert_eq!(to_camel_case("hello"), "helloWorker");
        assert_eq!(to_camel_case("my-api-server"), "myApiServerWorker");
    }

    #[test]
    fn test_to_camel_case_single_word() {
        assert_eq!(to_camel_case("app"), "appWorker");
    }

    #[test]
    fn test_to_camel_case_multiple_hyphens() {
        assert_eq!(to_camel_case("a-b-c-d"), "aBCDWorker");
    }

    #[test]
    fn test_entry_camel() {
        assert_eq!(entry_camel("my-blog"), "myBlogEntryWorker");
    }

    #[test]
    fn test_ssr_camel() {
        assert_eq!(ssr_camel("my-blog"), "myBlogSsrWorker");
    }

    #[test]
    fn test_static_camel() {
        assert_eq!(static_camel("my-blog"), "myBlogStaticWorker");
    }

    #[test]
    fn test_generate_dispatch_mjs_empty() {
        let apps: Vec<App> = vec![];
        let refs: Vec<&App> = apps.iter().collect();
        let code = generate_dispatch_mjs(&refs);
        assert!(code.contains("const routes = {\n};"));
        assert!(code.contains("export default"));
    }

    #[test]
    fn test_generate_dispatch_mjs_single_app() {
        let apps = vec![make_app("my-blog", "worker", "running")];
        let refs: Vec<&App> = apps.iter().collect();
        let code = generate_dispatch_mjs(&refs);
        assert!(code.contains(r#""my-blog": "APP_MY_BLOG""#));
    }

    #[test]
    fn test_generate_config_capnp_empty() {
        let apps: Vec<&App> = vec![];
        let config = generate_config_capnp(&apps, 8080);
        assert!(config.contains(r#"address = "*:8080""#));
        assert!(config.contains("dispatchWorker"));
        assert!(config.contains("main"));
    }

    #[test]
    fn test_generate_config_capnp_worker_app() {
        let apps = vec![make_app("my-api", "worker", "running")];
        let refs: Vec<&App> = apps.iter().collect();
        let config = generate_config_capnp(&refs, 8080);
        assert!(config.contains(r#"name = "app-my-api""#));
        assert!(config.contains("myApiWorker"));
        assert!(config.contains(r#"name = "APP_MY_API", service = "app-my-api""#));
    }

    #[test]
    fn test_generate_config_capnp_nuxtjs_app() {
        let apps = vec![make_app("my-blog", "nuxtjs", "running")];
        let refs: Vec<&App> = apps.iter().collect();
        let config = generate_config_capnp(&refs, 8080);
        assert!(config.contains(r#"name = "app-my-blog""#));
        assert!(config.contains(r#"name = "ssr-my-blog""#));
        assert!(config.contains(r#"name = "static-my-blog""#));
        assert!(config.contains("myBlogEntryWorker"));
        assert!(config.contains("myBlogSsrWorker"));
        assert!(config.contains("myBlogStaticWorker"));
    }

    #[test]
    fn test_generate_config_capnp_react_router_app() {
        let apps = vec![make_app("dashboard", "react-router", "running")];
        let refs: Vec<&App> = apps.iter().collect();
        let config = generate_config_capnp(&refs, 8080);
        assert!(config.contains(r#"name = "app-dashboard""#));
        assert!(config.contains(r#"name = "ssr-dashboard""#));
        assert!(config.contains(r#"name = "static-dashboard""#));
    }

    #[test]
    fn test_generate_config_capnp_multiple_apps() {
        let apps = vec![
            make_app("blog", "nuxtjs", "running"),
            make_app("api", "worker", "running"),
        ];
        let refs: Vec<&App> = apps.iter().collect();
        let config = generate_config_capnp(&refs, 9090);
        assert!(config.contains(r#"address = "*:9090""#));
        assert!(config.contains(r#"name = "app-blog""#));
        assert!(config.contains(r#"name = "app-api""#));
        assert!(config.contains(r#"name = "APP_BLOG", service = "app-blog""#));
        assert!(config.contains(r#"name = "APP_API", service = "app-api""#));
    }

    #[test]
    fn test_generate_dispatch_config_skips_missing_artifacts() {
        let dir = std::env::temp_dir().join("fugue-test-artifact-skip");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let apps = vec![make_app("missing-worker", "worker", "running")];
        generate_dispatch_config(&apps, &dir, 8080).unwrap();

        let config = std::fs::read_to_string(dir.join("config.capnp")).unwrap();
        assert!(!config.contains("missingWorker"));

        let dispatch = std::fs::read_to_string(dir.join("dispatch.mjs")).unwrap();
        assert!(!dispatch.contains("missing-worker"));
        assert!(dispatch.contains("export default"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_generate_dispatch_config_includes_app_with_artifacts() {
        let dir = std::env::temp_dir().join("fugue-test-artifact-include");
        let _ = std::fs::remove_dir_all(&dir);
        let slug_dir = dir.join("my-worker");

        std::fs::create_dir_all(&slug_dir).unwrap();
        std::fs::write(slug_dir.join("entry.mjs"), "").unwrap();
        std::fs::write(slug_dir.join("worker.js"), "").unwrap();
        std::fs::write(slug_dir.join("static-assets.mjs"), "").unwrap();

        let apps = vec![make_app("my-worker", "worker", "running")];
        generate_dispatch_config(&apps, &dir, 8080).unwrap();

        let config = std::fs::read_to_string(dir.join("config.capnp")).unwrap();
        assert!(config.contains("myWorker"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_generate_dispatch_config_writes_files() {
        let dir = std::env::temp_dir().join("fugue-test-config-gen");
        let _ = std::fs::remove_dir_all(&dir);
        let slug_dir = dir.join("test-app");
        std::fs::create_dir_all(&slug_dir).unwrap();
        std::fs::write(slug_dir.join("entry.mjs"), "").unwrap();
        std::fs::write(slug_dir.join("worker.js"), "").unwrap();
        std::fs::write(slug_dir.join("static-assets.mjs"), "").unwrap();

        let apps = vec![make_app("test-app", "worker", "running")];
        generate_dispatch_config(&apps, &dir, 8080).unwrap();

        let dispatch = std::fs::read_to_string(dir.join("dispatch.mjs")).unwrap();
        assert!(dispatch.contains("test-app"));

        let config = std::fs::read_to_string(dir.join("config.capnp")).unwrap();
        assert!(config.contains("app-test-app"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_has_required_artifacts_worker() {
        let dir = std::env::temp_dir().join("fugue-test-has-artifacts");
        let _ = std::fs::remove_dir_all(&dir);
        let slug_dir = dir.join("test-worker");
        std::fs::create_dir_all(&slug_dir).unwrap();

        let app = make_app("test-worker", "worker", "running");
        assert!(!has_required_artifacts(&app, &dir));

        std::fs::write(slug_dir.join("entry.mjs"), "").unwrap();
        std::fs::write(slug_dir.join("worker.js"), "").unwrap();
        std::fs::write(slug_dir.join("static-assets.mjs"), "").unwrap();
        assert!(has_required_artifacts(&app, &dir));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_has_required_artifacts_nuxtjs() {
        let dir = std::env::temp_dir().join("fugue-test-has-artifacts-nuxt");
        let _ = std::fs::remove_dir_all(&dir);
        let slug_dir = dir.join("test-nuxt");
        std::fs::create_dir_all(&slug_dir).unwrap();

        let app = make_app("test-nuxt", "nuxtjs", "running");
        assert!(!has_required_artifacts(&app, &dir));

        std::fs::write(slug_dir.join("entry.mjs"), "").unwrap();
        std::fs::write(slug_dir.join("bundle.mjs"), "").unwrap();
        std::fs::write(slug_dir.join("static-assets.mjs"), "").unwrap();
        assert!(has_required_artifacts(&app, &dir));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
