import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, extname } from "node:path";

const publicDir = join(process.cwd(), ".output/public");

const mimeTypes = {
  ".js": "application/javascript",
  ".mjs": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".html": "text/html",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".txt": "text/plain",
  ".xml": "application/xml",
};

function walk(dir) {
  const results = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walk(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

const files = walk(publicDir);
const entries = [];

for (const filePath of files) {
  const key = "/" + relative(publicDir, filePath);
  const ext = extname(filePath).toLowerCase();
  const mime = mimeTypes[ext] || "application/octet-stream";
  const content = readFileSync(filePath);
  const b64 = content.toString("base64");
  entries.push(`[${JSON.stringify(key)}, { mime: ${JSON.stringify(mime)}, data: "${b64}" }]`);
}

const code = `// Auto-generated by embed-assets.mjs — do not edit
const assets = new Map([${entries.join(",\n")}]);
export default assets;
`;

writeFileSync("static-assets.mjs", code);
console.log(`Embedded ${files.length} static assets into static-assets.mjs`);
